### ISSUE TITLE
 _WINSOCK_DEPRECATED_NO_WARNINGS needed for building tcpmodem.c

### ISSUE THREAD

**Issue by LowLevelMahn** [mikechambers84/XTulator#1]
fresh clone:
  last submit:
  3 days ago (08.07.2020 19:06:09)
  Commit hash: 6f182c2465c93be9effac056d513109de515e49e

current SDL2 dev: SDL2-2.0.12 and latest VS2019

latest Win7 x64

XTulator\XTulator\modules\io\tcpmodem.c(120,12): error C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

#define _WINSOCK_DEPRECATED_NO_WARNINGS

as first defined in tcpmodem.c fixes the build for me

**Comment by mikechambers84** [comment]
I must have left that out in one of the build configurations. Though what I really need to do is stop using deprecated functions. :)

At some point in the near future, I was going to make a sockets abstraction layer that gives me a single API to interface with, but that works on any OS... putting the platform-specific code all in the abstraction layer.

**Comment by mikechambers84** [comment]
Fixed! I accidentally left it out of one of the debug configs. Thanks.
